(require 'common_functions.lisp)
(setf lines (openFile "and_examples.txt"))
;(print lines)
;(setf x (openFile "and.lisp"))
(setf specs_collection (transform_1 (list #'split lines " ")))
;(print (transform #'print_ (list 1 2 3)))
;(print (passToSplit #'split (list :strings (list "212221233" "212221212") :delimiter "12")))
;(print (split "212221212" "12"))
;(print specs)
;(setf specs (passToSplit #'split (list :strings lines :delimiter " ")))
;(terpri)
;(terpri)
;(print specs_collection)
;(quit)
;(terpri)

(setf *python_base_elements* (list "0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "and" "or" "if"))
(setf *knowledge* (object  "" nil nil nil))
;(quit)

; check python_base_elements to see if specs is in it
;(setf specs_k_u_collection (searchSpecs specs_collection python_base_elements))
;(quit)
;(terpri)
;(print specs_k_u_collection)
;(quit)
;(traverseLists specs_collection)
(processEachSpecs specs_collection)
;(print knowledge)
(terpri)
(terpri)
(print "knowledge")
(print *knowledge*)
;(terpri)
;(terpri)

